### PR TITLE
Add option to return stderr

### PR DESCRIPTION
**Pull request by QORTEC**
FFprobe outputs "debug" information to stderr. I have a edge case where I need to parse specific information only found in stderr.

````
print ffmpy.FFprobe(
    inputs={'test.aax' : None},
    global_options='-hide_banner'
).run(return_stderr=True)
````
Returns normal FFprobe stderr output

````
print ffmpy.FFprobe(
    inputs={'test.aax' : None},
    global_options='-hide_banner'
).run()
````
Returns ``None``

### CODE REVIEW

**Comment by Ch00k** [comment]
@QORTEC I'd rather not introduce a new argument, but instead would return `out` entirely. This way the `run` method will always return a 2-tuple `(stdout, stderr)`, which you can then check for whether it contains any actual stdout/stderr output (which will be there only if `verbose` is `True`).

**Comment by QORTEC** [comment]
Thank you @Ch00k, I think that will solve my issue.

**Comment by QORTEC** [comment]
When I originally read you post I though you wanted to *only return a 2-tuple on verbose*, though after reading your post I think I misunderstood.

@Ch00k 
>This way the ``run`` method will always return a 2-tuple ``(stdout, stderr)``


However in the  current implementation 11e62738f0651f69c16611e758aafa52c04faded; the ``run`` method will it will *always return a 2-tuple* and *output both ``stdout, stderr``*. If fairly sure this was not your original intention.

@Ch00k; 
>which will be there only if ``verbose`` is ``True``

**Comment by Ch00k** [comment]
@QORTEC It is not correct. I am now working on a new version that will allow explicitly specifying whether or not you want to keep (return) stdout/stderr.

**Comment by Ch00k** [comment]
@QORTEC New version is ready. It's now possible to explicitly redirect stdout and stderr so that they are returned afterwards.

**Comment by QORTEC** [comment]
Thank you, @Ch00k

**Pull request closed without merging**
